general:
  instance_name: disabled
  debug: false

limiter:
  static_use_hash: false
  network:
    source_ips:
      - 0.0.0.0/0
      - "::/0"
    source_ip_methods:
      - X-Forwarded-For
      - X-Real-IP
      - Remote-Addr
    always_trust_forwarded_for: true

botdetection:
  http_protocol_version: "1.1"
  coincidence_level: 0
